### ISSUE TITLE
multiple output of classes

### ISSUE THREAD

**Issue by hellatan** [antialias/scss-alignment-transforms#1]
When the main scss file is imported inside multiple files, the below source (along with any classes extending these placeholders) are output into the final output file multiple times:

``` css
.class__verticallyCentered___hash {
  position: absolute;
  top: 50%;
  -webkit-transform: translateY(-50%);
      -ms-transform: translateY(-50%);
          transform: translateY(-50%);
}

.class__horizontallyRight___hash {
  position: absolute;
  right: 0;
}

.class__horizontallyCentered___hash {
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
      -ms-transform: translateX(-50%);
          transform: translateX(-50%);
}

.class__verticallyHorizontallyCentered___hash {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translateY(-50%) translateX(-50%);
      -ms-transform: translateY(-50%) translateX(-50%);
          transform: translateY(-50%) translateX(-50%);
}
```

Imagine you have `_file1.scss`, `_file2.scss`, and `output.scss`:

``` scss
// _file1.scss
@import "~scss-alignment-transforms";
@import "some-local-file";

.file1 { display: inline; }
```

``` scss
// _file2.scss
@import "~scss-alignment-transforms";
@import "some-local-file2";

.file2 { display: block; }
```

``` scss
// output.scss
@import "_file1";
@import "_file2";

// output some styles
```

once `output.scss` is compiled, it ends up looking something like this:

``` css
.class__verticallyCentered___hash {
  position: absolute;
  top: 50%;
  -webkit-transform: translateY(-50%);
      -ms-transform: translateY(-50%);
          transform: translateY(-50%);
}

.class__horizontallyRight___hash {
  position: absolute;
  right: 0;
}

.class__horizontallyCentered___hash {
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
      -ms-transform: translateX(-50%);
          transform: translateX(-50%);
}

.class__verticallyHorizontallyCentered___hash {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translateY(-50%) translateX(-50%);
      -ms-transform: translateY(-50%) translateX(-50%);
          transform: translateY(-50%) translateX(-50%);
}

// some local file output

.file1 { display: inline; }

.class__verticallyCentered___hash {
  position: absolute;
  top: 50%;
  -webkit-transform: translateY(-50%);
      -ms-transform: translateY(-50%);
          transform: translateY(-50%);
}

.class__horizontallyRight___hash {
  position: absolute;
  right: 0;
}

.class__horizontallyCentered___hash {
  position: absolute;
  left: 50%;
  -webkit-transform: translateX(-50%);
      -ms-transform: translateX(-50%);
          transform: translateX(-50%);
}

.class__verticallyHorizontallyCentered___hash {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translateY(-50%) translateX(-50%);
      -ms-transform: translateY(-50%) translateX(-50%);
          transform: translateY(-50%) translateX(-50%);
}

// some more local file output

.file2 { display: block }
```
